
import { ChakraProvider } from "@chakra-ui/react";
import "@rainbow-me/rainbowkit/styles.css";
import type { AppProps } from "next/app";
import Head from "next/head";
import { WagmiConfig, configureChains, createConfig, sepolia } from "wagmi";
import { alchemyProvider, } from 'wagmi/providers/alchemy';
import { theme } from "../theme";

import {
  RainbowKitProvider,
  darkTheme,
  getDefaultWallets,
} from "@rainbow-me/rainbowkit";


const { chains, publicClient, webSocketPublicClient } = configureChains(
  [sepolia],
  [
    alchemyProvider({apiKey: String(process.env.NEXT_PUBLIC_ALCHEMY_API_KEY)}),
  ]
);

const { connectors } = getDefaultWallets({
  appName: "wPOKT Bridge",
  projectId: `${process.env.NEXT_PUBLIC_APP_PROJECT_ID}`,
  chains,
});

const config = createConfig({
  autoConnect: true,
  connectors,
  publicClient,
  webSocketPublicClient,
});

export default function App({ Component, pageProps }: AppProps | any) {
  return (
    <>
      <Head>
        <title>wPOKT Staking</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <WagmiConfig config={config}>
        <RainbowKitProvider
          chains={chains}
          theme={darkTheme({
            accentColor: "rgba(185, 240, 0, 1)",
            fontStack: "system",
            overlayBlur: "small",
            borderRadius: "small",
          })}
        >
          <ChakraProvider theme={theme}>
            <Component {...pageProps} />
          </ChakraProvider>
        </RainbowKitProvider>
      </WagmiConfig>
    </>
  );
}
